services:

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: bn_opencart
    ports:
      - "8082:80"

  mariadb:
    image: bitnami/mariadb:11.2
    platform: linux/amd64
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_USER: bn_opencart
      MARIADB_DATABASE: bitnami_opencart
    ports:
      - "3306:3306"

  opencart:
    image: agridyaev/opencart:4.0.2-3-debian-12-r33
    platform: linux/amd64
    environment:
      OPENCART_HOST: "localhost:8081"
      OPENCART_DATABASE_HOST: mariadb
      OPENCART_DATABASE_PORT_NUMBER: 3306
      OPENCART_DATABASE_USER: bn_opencart
      OPENCART_DATABASE_NAME: bitnami_opencart
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8081:8080"
      - "8443:8443"
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3


